export const GET_ERRORS = "GET_ERRORS";
export const USER_LOADING = "USER_LOADING";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const SET_ALL_PRODUCT  = "SET_ALL_PRODUCT";
export const ADD_PRODUCT_SUCCESS = "ADD_PRODUCT_SUCCESS";
export const GET_ALL_ORDERS_SUCCESS = "GET_ALL_ORDERS_SUCCESS";
export const GET_ALL_PRODUCT_SUCCESS = "GET_ALL_PRODUCT_SUCCESS";
export const SET_CURRENT_CART = "SET_CURRENT_CART";
export const SET_RESTURANT_AUTH = "SET_RESTURANT_AUTH";
export const SET_CUSTOMER_AUTH  = "SET_CUSTOMER_AUTH";
export const SET_CART_ITEM = "SET_CART_ITEM";
export const CREATE_ORDER = "CREATE_ORDER";
export const SET_CUSTOMER_LOGOUT = "SET_CUSTOMER_LOGOUT";
export const SET_CUSTOMER_HISTORY = "SET_CUSTOMER_HISTORY";


